//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LastLab
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class METROEntities : DbContext
    {
        public METROEntities()
            : base("name=METROEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccessRank> AccessRank { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Cheque> Cheque { get; set; }
        public virtual DbSet<Cost> Cost { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Purchase> Purchase { get; set; }
        public virtual DbSet<Sitizenship> Sitizenship { get; set; }
        public virtual DbSet<Trader> Trader { get; set; }
        public virtual DbSet<TypeOfInterraction> TypeOfInterraction { get; set; }
    }
}
